services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - ${HOST_PORT}:3000
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_ENV: ${ENVIRONMENT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    env_file: .env
    depends_on:
      - db

volumes:
  mysql_data: