default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password: <%= ENV['ROOT_PASS'] %>
  host: db
  database: sort-assist_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password: <%= ENV['ROOT_PASS'] %>
  host: db
  database: sort-assist_test

production:
  <<: *default
  adapter: mysql2
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  socket: /var/run/mysqld/mysqld.sock
  database: sort-assist_production